### ISSUE TITLE
openplanner 1.13 vs openplanner 1.15

### ISSUE THREAD

**Issue by sethut1224** [hatem-darweesh/core_planning#14]
Hatem,
Thanks for what you've worked so far to make openplanner 1.13 and openplanner 1.15
I have been using your openplanner 1.13 

I have a question about 1.13 vs 1.15
Is there any different between 1.13 and 1.15?(except a dependency of Autoware version)

thanks

**Comment by hatem-darweesh** [comment]
@sethut1224  Nothing , both are the same code base.

**Comment by sethut1224** [comment]
@hatem-darweesh 
thanks for the clear answer
