### ISSUE TITLE
Map loading code duplication.

### ISSUE THREAD

**Issue by MaxandreOgeret** [hatem-darweesh/core_planning#3]
I was about to start adding a parameter to select the velocity unit of the vector map to accommodate everyone. (All our maps are in meter per second).

I think adding a new `enum` in `RoadNetwork.h` named `MAP_VELOCITY_UNIT` is a good solution : 

```cpp
enum MAP_VELOCITY_UNIT {
        KPH, // kilometer per hour
        MPS  // meter per second
};
```

The velocity unit would then be determined by a parameter like it is done already for the map type : 

```cpp
        int iVelUnit;
        _nh.getParam("/op_common_params/velocity_unit" , iSource);
        if (iVelUnit == 0) {
          m_VelocityUnit = PlannerHNS::KPH;
        } else if (iVelUnit == 1) {
          m_VelocityUnit = PlannerHNS::MPS;
        }
```

But the problem I face is that the map is actually loaded and the velocity converted is several places. Here are all the places where the velocity can be converted : 

![image](https://user-images.githubusercontent.com/22786578/121186794-1fc79d00-c870-11eb-986f-2609ea303c6b.png)

Adding a condition to all of those would add a lot of unwanted complexity.

It seems to me that the map loading code is duplicating at in the following files : 

- `op_signs_simulator_core.cpp`
- `op_behavior_selector_core.cpp`
- `op_motion_predictor_core.cpp`
- `op_data_logger.cpp`

I believe the map loading code should be taken apart and then mutualized. 
What do you think ? Any guidelines to do so ?

Thanks !

**Comment by hatem-darweesh** [comment]
I agree with you. 
Mapping functions will be added in op_ros_helpers. 
we add new class, 
all required mapping functions will be added as static functions. 
these functions will be called when required. 
it shouldn't take long time.

**Comment by MaxandreOgeret** [comment]
I'll try to book some time next week to propose a pull request. I'll keep you in touch ! :)

**Comment by hatem-darweesh** [comment]
Fixed by commits: 
https://github.com/hatem-darweesh/core_planning/commit/e40ba73c9979649388aa28aa2016743bc7da73b5
https://github.com/hatem-darweesh/core_planning/commit/6838f675ce6b4be5e4c973e4587efc7adcc8a2d0
https://github.com/hatem-darweesh/core_planning/commit/4e972ce4d8e412a2f590a931197130d51801e812
