### ISSUE TITLE
Traffic Light Recognition + Open Planner

### ISSUE THREAD

**Issue by ParthAD3** [hatem-darweesh/core_planning#6]
Hi,
this is Thiago de Borba from the working group.
In the moment I am testing Open Planner with different scenarios in Carla + Autoware 1.14.
I am trying to implement traffic light recognition to test Open Planner in traffic light stop scenario.
I have a vector map with traffic light data, when I launch the feature_projection node, it publishes the Roi_signal topic with no data.
Could you help me fix this problem?

**Comment by thiagodeborba** [comment]
If necessary I can tape a small video to explain the problem.

**Comment by hatem-darweesh** [comment]
Are you still facing this issue ?

**Comment by thiagodeborba** [comment]
> Are you still facing this issue ?

Hello @hatem-darweesh ,

Yes, I am still facing this problem.
Any suggestion?

**Comment by hatem-darweesh** [comment]
Check these information, they may help. 
also of you are using KML maps, you can use feat_proj_kml node 

![Autoware 1 13 Docs](https://user-images.githubusercontent.com/20182801/133046336-b60b0339-acd0-452e-b5c9-bc475d096cc3.png)

If not, you can record a video explaining practically your issue.
