### ISSUE TITLE
Autoware 1.14

### ISSUE THREAD

**Issue by tugstugi** [hatem-darweesh/core_planning#9]
@hatem-darweesh I am interested in using lanelet2 with OpenPlanner in Autoware 1.14. In this repo, there are branches for Autoware 1.13 and 1.15 but not 1.14. My questions are:
* does the stock Autoware 1.14 support planning with lanelet2?
* if not, do you plan make a support for 1.14?

Greetings
Tuguldur

**Comment by hatem-darweesh** [comment]
Sorry we are not supporting 1.14, the reason is lanelet2 support is stable and much better than in 1.15. 
that is why we skipped creating a special merge to release 1.15. 
I guess you can use 1.15 safely , we conducted several tests with OpenPlanner and it seems to work fine.
